repos:
  # Core pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  # Terraform hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      # Format and validate Terraform files
      - id: terraform_fmt
      - id: terraform_validate

      # Generate documentation
      - id: terraform_docs
        args: [--args=--lockfile=false]


  # Trivy security scanning
  #- repo: https://github.com/aquasecurity/trivy
  #  rev: v0.45.1
  #  hooks:
  #    - id: trivy-config
  #      args: [ .]  # Filtre les vulnérabilités affichées.
