name: Terratest - EKS Validation
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  terratest:
    name: Run Terratest
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "us-east-1"
      TF_VAR_cluster_name: "eks-test-${{ github.run_id }}"

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configure AWS Credentials (from GitHub Secrets)
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Install dependencies
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y golang wget unzip
          
          wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
          unzip terraform_1.6.6_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          
          go install github.com/gruntwork-io/terratest/modules/aws@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      # 4. Initialize Terraform
      - name: Terraform Init
        run: |
          cd examples/basic-eks
          terraform init

      # 5. Run Terratest
      - name: Execute Tests
        run: |
          cd tests/terratest
          go mod init terratest
          go mod tidy
          go test -v -timeout 20m -run TestKubernetesAccess

      # 6. Cleanup (always runs, even if tests fail)
      - name: Destroy Infrastructure
        if: always()
        run: |
          cd examples/basic-eks
          terraform destroy -auto-approve
