name: Trivy Security Scan
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
#  schedule:
#    - cron: '0 0 * * *'  # Daily scan

jobs:
  trivy-scan:
    name: Run Trivy Scanner
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # For GitHub Code Scanning alerts

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # Run Trivy scan (config + sensitive)
      - name: Scan Terraform files
        run: |
          trivy config .

      # Upload results to GitHub Security tab
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      # Fail workflow on critical findings
      - name: Check for critical vulnerabilities
        if: success()
        run: |
          if grep -q '"level": "error"' trivy-results.sarif; then
            echo "::error::Critical vulnerabilities found!"
            exit 1
          fi
